version: "2"
plugins:
  sonar-python:
    enabled: true
exclude_patterns:
  - "spec/"
  - "!spec/support/helpers"
  - "config/"
  - "src/alembic/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
