@startuml
allowmixing
skinparam componentStyle uml1

package celery_worker {}

package http_app #fff {
    package routes #DDDDDD
}

package grpc_app #fff {
    package servicers #DDDDDD
}

package domains #DDDDDD {
    package books {
        class Book
        class BookService

        package entities {
            class BookModel
            class BookEvent
        }

        package tasks {
            class BookTask
        }

        package data_access_interface {
            protocol BookRepositoryInterface
            protocol BookEventGatewayInterface
        }
    }
}

package gateways #DDDDDD {
    class SQLAlchemyRepository
    class NullEventGateway
}


'links framework - domains
routes --> BookService
routes --> Book
servicers --> BookService
servicers --> Book
celery_worker ---> tasks
tasks <-u-> BookService
tasks -u-> Book

'links internal to books domain
BookService -l-> Book
BookService --> entities
BookService -r-> data_access_interface
data_access_interface --> entities

'links domains - gateways
gateways --|> data_access_interface: implements >

@enduml
