version: '3.8'
services:
  dev:
    build:
      dockerfile: Dockerfile
      context: .
      target: http_app
    ports:
      - '8000:8000'
    command: ["make", "dev"]
    volumes:
      - '.:/app'
  http:
    build:
      dockerfile: Dockerfile
      context: .
      target: http_app
    environment:
      OTEL_SERVICE_NAME: "bootstrap-fastapi"
      OTEL_TRACES_EXPORTER: "console"
      OTEL_METRICS_EXPORTER: "console"
      OTEL_LOGS_EXPORTER: "none"
    ports:
      - '8001:8000'
    volumes:
      - './sqlite.db:/app/sqlite.db'

  generate-proto:
    build:
      dockerfile: Dockerfile
      context: .
      target: grpc_builder
    volumes:
      - '.:/app'
    command: ["make", "generate-proto"]

  grpc:
    build:
      dockerfile: Dockerfile
      context: .
      target: grpc_app
    environment:
      OTEL_SERVICE_NAME: "bootstrap-fastapi"
      OTEL_TRACES_EXPORTER: "console"
      OTEL_METRICS_EXPORTER: "console"
      OTEL_LOGS_EXPORTER: "none"
    ports:
      - "50051:50051"
    volumes:
      - '.:/app'

  test:
    build:
      dockerfile: Dockerfile
      context: .
      target: test
    volumes:
      - '.:/app'
    command: ["make", "test"]
