version: '3.8'
services:
  # We don't use `make` or `poetry` for long running processes,
  # to make sure they run as pid 1 and receive SIGTERM signal
  dev:
    build:
      dockerfile: Dockerfile
      context: .
      target: http_app
    ports:
      - '8000:8000'
    command:
      - "uvicorn"
      - "http_app:create_app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--factory"
      - "--reload"
    volumes:
      - '.:/app'
  http:
    build:
      dockerfile: Dockerfile
      context: .
      target: http_app
    environment:
      OTEL_SERVICE_NAME: "bootstrap-fastapi"
      OTEL_TRACES_EXPORTER: "console"
      OTEL_METRICS_EXPORTER: "console"
      OTEL_LOGS_EXPORTER: "none"
    ports:
      - '8001:8000'
    volumes:
      - './sqlite.db:/app/sqlite.db'

  grpc:
    build:
      dockerfile: Dockerfile
      context: .
      target: grpc_app
    environment:
      OTEL_SERVICE_NAME: "bootstrap-fastapi"
      OTEL_TRACES_EXPORTER: "console"
      OTEL_METRICS_EXPORTER: "console"
      OTEL_LOGS_EXPORTER: "none"
    ports:
      - "9999:9999"
    volumes:
      - '.:/app'

  # Starting from here there are only single-run commands, we can use `make` here
  generate-proto:
    build:
      dockerfile: Dockerfile
      context: .
      target: grpc_builder
    volumes:
      - '.:/app'
    command:
      - "make"
      - "generate-proto"

  test:
    build:
      dockerfile: Dockerfile
      context: .
      target: test
    volumes:
      - '.:/app'
    command:
      - "make"
      - "test"

  ci-test:
    build:
      dockerfile: Dockerfile
      context: .
      target: test
    command:
      - "make"
      - "ci-test"
