version: '3'
services:
  webapp:
    build: .
    ports:
      - '8000:8000'
    command:
      - 'poetry'
      - 'run'
      - 'uvicorn'
      - 'app:create_app'
      - '--host'
      - '0.0.0.0'
      - '--port'
      - '8000'
      - '--factory'
      - '--reload'
    volumes:
      - '.:/app'
