version: '3'
services:
  dev:
    build: .
    ports:
      - '8000:8000'
    command:
      - 'uvicorn'
      - 'http_app:create_app'
      - '--host'
      - '0.0.0.0'
      - '--port'
      - '8000'
      - '--factory'
      - '--reload'
    volumes:
      - '.:/app'
  app:
    build: .
    ports:
      - '8001:8000'
    volumes:
      - './sqlite.db:/app/sqlite.db'

  generate-proto:
    build: .
    volumes:
      - '.:/app'
    working_dir: "/app/grpc_app/"
    command: ["make", "generate-proto"]

  grpc_app:
    build: .
    ports:
      - "50051:50051"
    volumes:
      - '.:/app'
    command: ["python3", "-m", "grpc_app"]
