version: '3'
services:
  dev:
    build: .
    ports:
      - '8000:8000'
    command: ["make", "dev"]
    volumes:
      - '.:/app'
  app:
    build: .
    ports:
      - '8001:8000'
    volumes:
      - './sqlite.db:/app/sqlite.db'

  generate-proto:
    build: .
    volumes:
      - '.:/app'
    working_dir: "/app/grpc_app/"
    command: ["make", "generate-proto"]

  grpc:
    build: .
    ports:
      - "50051:50051"
    volumes:
      - '.:/app'
    command: ["make", "grpc"]
