version: '3'
services:
  dev:
    build: .
    ports:
      - '8000:8000'
    command:
      - 'uvicorn'
      - 'http_app:create_app'
      - '--host'
      - '0.0.0.0'
      - '--port'
      - '8000'
      - '--factory'
      - '--reload'
    volumes:
      - '.:/app'
  app:
    build: .
    ports:
      - '8001:8000'
    volumes:
      - './sqlite.db:/app/sqlite.db'
