services:
  dev-http: &dev
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    env_file: docker.env
    environment:
      APP_NAME: "backend-fastapi"
    ports:
      - '8000:8000'
    working_dir: "/app/src"
    volumes:
      - '.:/app'
    depends_on:
      redis:
        condition: service_healthy
      otel-collector:
        condition: service_started
      mariadb:
        condition: service_healthy
    command:
      - python
      - ./http_app/dev_server.py

  dev-socketio:
    <<: *dev
    environment:
      APP_NAME: "backend-socketio"
    ports:
      - '8001:8001'
    command:
      - python
      - ./socketio_app/dev_server.py

  #########################
  #### Helper services ####
  #########################

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans

  otel-collector:
    image: grafana/alloy:latest
    # You can add the Grafana Cloud credentials in this file
    # and push observability directly to the provider.
    # Refer to the config.alloy file to see what credentials we need.
    env_file:
      - path: ./credentials.env
        required: false
    depends_on:
      - jaeger
    ports:
      - "12345:12345"
      - "4317:4317"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=experimental
#      - --stability.level=public-preview
      - /etc/alloy/config.alloy

  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mariadb:
    image: mariadb:11.7
    environment:
      MYSQL_ROOT_PASSWORD: "stanis"
      MYSQL_DATABASE: "backend"
      MYSQL_USER: "corinna"
      MYSQL_PASSWORD: "gioieiiere"
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  dramatiq-worker:
    <<: *dev
    environment:
      APP_NAME: "backend-dramatiq-worker"
    ports: []
    command:
      - dramatiq
      - --watch
      - .
      - -p
      - "1"
      - -t
      - "1"
      - dramatiq_worker

  #################################
  #### Authentication services ####
  #################################

  kratos-migrate:
    image: oryd/kratos:v1.3.1
    environment:
      DSN: "sqlite:///etc/config/kratos/db.sqlite?_fk=true&mode=rwc"
    volumes:
      - ./auth_volumes/kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.3.1
    # It's not needed to expose these, leaving for documentation
#    ports:
#      - '4433:4433' # public API
#      - '4434:4434' # admin API
    restart: unless-stopped
    environment:
      DSN: "sqlite:///etc/config/kratos/db.sqlite?_fk=true&mode=rwc"
      LOG_LEVEL: "trace"
    volumes:
      - ./auth_volumes/kratos:/etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier

  auth-ui:
    image: oryd/kratos-selfservice-ui-node:v1.3.1
    environment:
      PORT: 3000
      # Internal access URL for the BFF instance
      KRATOS_PUBLIC_URL: "http://kratos:4433/"
      # External access URL for the browser
      KRATOS_BROWSER_URL: "http://127.0.0.1:8080/.ory/kratos/public"
      JWKS_URL: "http://oathkeeper:4456/.well-known/jwks.json"
      SECURITY_MODE: "jwks"
      COOKIE_SECRET: "changeme"
      CSRF_COOKIE_NAME: "ory_csrf_ui"
      CSRF_COOKIE_SECRET: "changeme"
    restart: on-failure

#  mailslurper:
#    image: oryd/mailslurper:latest-smtps
#    ports:
#      - '4436:4436'
#      - '4437:4437'

  oathkeeper:
    image: oryd/oathkeeper:v0.40.9
    depends_on:
      - kratos
      - auth-ui
      - dev-http
    ports:
      # Public traffic port
      - "8080:4455"
      # Private traffic port, this is not usually exposed
      # among other things it provides the JWKS url
      # - "4456:4456"
    command:
      serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    restart: on-failure
    volumes:
      - ./auth_volumes/oathkeeper:/etc/config/oathkeeper

  ##########################
  #### One-off commands ####
  ##########################
  test:
    <<: *dev
    environment:
      APP_NAME: "backend-test"
    ports: []
    command:
      - "make"
      - "test"

  migrate:
    <<: *dev
    environment:
      APP_NAME: "backend-migrations"
    ports: []
    command:
      - "alembic"
      - "upgrade"
      - "heads"

  autogenerate-migration:
    <<: *dev
    environment:
      APP_NAME: "backend-migration-generator"
    ports: []
    command:
      - "alembic"
      - "revision"
      - "--autogenerate"
      - "-m"
      - "Description message"
