# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Bootstrap python fastapi
site_description: 'A template for a python web service written applying Clean Architecture concepts'
site_author: 'Federico Busetti'
docs_dir: docs/
repo_name: 'febus982/bootstrap-python-fastapi'
repo_url: 'https://github.com/febus982/bootstrap-python-fastapi'

plugins:
  - search
  - awesome-pages
  - macros:
      modules:
        - mkdocs_macros_adr_summary
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(window.localStorage.getItem('/.__palette')).index == 1) ? 'dark' : 'neutral'

# Do not use the nav section in this file but reference to the .pages files
# in the docs/ directory and subdirectories (awesome-pages plugin)
# https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
#nav:
#  - Home: index.md

theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
    - content.code.copy

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to auto mode

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/federico-b-a0b78232

markdown_extensions:
  - pymdownx.details
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
