[tool.poetry]
name = "bootstrap-fastapi-service"
version = "0.1.0"
description = ""
authors = ["Federico Busetti <729029+febus982@users.noreply.github.com>"]
readme = "README.md"

# https://python-poetry.org/docs/dependency-specification
[tool.poetry.dependencies]
aiosqlite = ">=0.18.0"
alembic = "^1.11.1"
dependency-injector = { version = "^4.41.0", extras = ["pydantic"] }
httpx = ">=0.23.0"
opentelemetry-distro = { version = "*", extras = ["otlp"] }
opentelemetry-instrumentation = "*"
opentelemetry-instrumentation-httpx = "*"
opentelemetry-instrumentation-sqlalchemy = "*"
pydantic = "^2.2.1"
pydantic-settings = "^2.0.3"
python = ">=3.9,<3.12"
rich = "^13.2.0"
SQLAlchemy = { version = "^2.0.0", extras = ["asyncio", "mypy"] }
sqlalchemy-bind-manager = "*"
structlog = "^23.1.0"
cloudevents = "^1.9.0"

[tool.poetry.group.http]
optional = true

[tool.poetry.group.http.dependencies]
fastapi = ">=0.99.0"
jinja2 = "^3.1.2"
opentelemetry-instrumentation-fastapi = "*"
starlette-prometheus = "^0.9.0"
strawberry-graphql = { version = ">=0.204.0", extras = ["debug-server"] }
uvicorn = { version = "^0.21.0", extras = ["standard"] }
fastapi-cloudevents = "^1.1.0"

[tool.poetry.group.grpc]
optional = true

[tool.poetry.group.grpc.dependencies]
grpcio = "^1.51.1"
grpcio-tools = "^1.51.1"
grpc-stubs = "^1.24.11"
mypy-protobuf = "^3.4.0"
opentelemetry-instrumentation-grpc = "*"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
asynctest = "*"
coverage = "*"
black = "*"
mypy = "*"
mypy-protobuf = "*"
pytest = "*"
pytest-cov = "*"
pytest-factoryboy = "*"
pytest-xdist = "*"
ruff = "*"
strawberry-graphql = { version = "*", extras = ["debug-server", "fastapi"] }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-n auto --cov-report=term-missing"
testpaths = [
    "tests",
]

[tool.mypy]
files = [
    "domains",
    "grpc_app",
    "http_app",
    "gateways",
    "tests",
    "di_container.py",
    "config.py",
]
plugins = "pydantic.mypy,strawberry.ext.mypy_plugin"

[[tool.mypy.overrides]]
module = "grpc.aio.*"
ignore_missing_imports = true

[tool.ruff]
select = ["E", "F", "I"]
exclude = [
    "grpc_app/generated",
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.black]
files = '''
(
  http_app
  grpc_app
  domains
  gateways
  tests
  alembic
)
'''
extend-exclude = '''
(
  /grpc_app/generated
)
'''
