[tool.poetry]
name = "bootstrap-fastapi-service"
version = "0.1.0"
description = ""
authors = ["Federico Busetti <729029+febus982@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "bootstrap_fastapi_service"}]

[tool.poetry.dependencies]
alembic = "~1.8.1"
attrs = "~22.1.0"
dependency-injector = { version = "~4.40.0", extras = ["pydantic"] }
fastapi = "~0.86.0"
httpx = "~0.23.0"
python = "~3.10"
uvicorn = "~0.19.0"
SQLAlchemy = { version = "~1.4.43", extras = ["asyncio"] }

[tool.poetry.group.dev.dependencies]
pytest = "~7.2.0"
coverage = "~6.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
