[tool.poetry]
name = "bootstrap-fastapi-service"
version = "0.1.0"
description = ""
authors = ["Federico Busetti <729029+febus982@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "bootstrap_fastapi_service"}]

[tool.poetry.dependencies]
alembic = "~1.8.1"
attrs = "~22.1.0"
dependency-injector = { version = "~4.40.0", extras = ["pydantic"] }
fastapi = "~0.86.0"
httpx = "~0.23.0"
python = "~3.10"
SQLAlchemy = { version = "~1.4.43", extras = ["asyncio"] }
starlette-prometheus = "~0.9.0"
uvicorn = "~0.19.0"

[tool.poetry.group.dev.dependencies]
coverage = "~6.5.0"
black = "~22.10.0"
flake8 = "~5.0.4"
mypy = "~0.990"
pytest = "~7.2.0"
pytest-cov = "^4.0.0"
pytest-factoryboy = "~2.5.0"
pytest-xdist = "^3.0.2"
sqlalchemy-stubs = "^0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
