[tool.poetry]
name = "bootstrap-fastapi-service"
version = "0.1.0"
description = ""
authors = ["Federico Busetti <729029+febus982@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
aiosqlite = "^0.18.0"
alembic = "~1.9.2"
dependency-injector = { version = "~4.41.0", extras = ["pydantic"] }
httpx = "~0.23.0"
opentelemetry-distro = "^0.36b0"
opentelemetry-exporter-otlp = "^1.15.0"
opentelemetry-instrumentation-httpx = "^0.36b0"
opentelemetry-instrumentation-sqlalchemy = "^0.36b0"
python = ">=3.9,<3.12"
rich = "^13.2.0"
SQLAlchemy = { version = "~2.0.0", extras = ["asyncio", "mypy"] }
sqlalchemy-bind-manager = "*"
structlog = "~22.3.0"

[tool.poetry.group.http]
optional = true

[tool.poetry.group.http.dependencies]
fastapi = "~0.87.0"
fastapi-versionizer = "~0.1.2"
jinja2 = "~3.1.2"
opentelemetry-instrumentation-fastapi = "^0.36b0"
starlette-prometheus = "~0.9.0"
uvicorn = { version = "~0.20.0", extras = ["standard"] }

[tool.poetry.group.grpc]
optional = true

[tool.poetry.group.grpc.dependencies]
grpcio = "~1.51.1"
grpcio-tools = "~1.51.1"
grpc-stubs = "~1.24.11"
mypy-protobuf = "^3.4.0"
opentelemetry-instrumentation-grpc = "^0.36b0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
asynctest = "^0.13.0"
coverage = "~6.5.0"
black = "~22.10.0"
flake8 = "~5.0.4"
mypy = "~0.990"
mypy-protobuf = "~3.4.0"
pytest = "~7.2.0"
pytest-cov = "^4.0.0"
pytest-factoryboy = "~2.5.0"
pytest-xdist = "^3.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-n auto --cov-report=term-missing"
testpaths = [
    "tests",
]

[tool.mypy]
files = [
    "domains",
    "grpc_app",
    "http_app",
    "storage",
    "tests",
    "di_container.py",
    "config.py",
]

[[tool.mypy.overrides]]
module = "grpc.aio.*"
ignore_missing_imports = true
