# Build Docker image for test
build-test:
  stage: build
  variables:
    DOCKER_IMAGE_NAME: $CI_PROJECT_NAME-test
    DOCKER_TARGET: dev
  rules:
    # We run the pipeline only on merge requests or the `main` branch
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  extends:
    - .build-and-push-gitlab

# TODO: Make the multi-arch build in a single job (perhaps with a nested workflow)
build-http-app-amd64:
  stage: build
  variables:
    DOCKER_IMAGE_NAME: $CI_PROJECT_NAME-http
    DOCKER_PLATFORM: "linux/amd64"
    DOCKER_TARGET: http
  tags:
    - saas-linux-small-amd64
  rules:
    # We run the pipeline only on merge requests or the `main` branch
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  extends:
    - .build-and-push-gitlab

build-http-app-arm64:
  stage: build
  variables:
    DOCKER_IMAGE_NAME: $CI_PROJECT_NAME-http
    DOCKER_PLATFORM: "linux/arm64"
    DOCKER_TARGET: http
  tags:
    - saas-linux-small-arm64
  rules:
    # We run the pipeline only on merge requests or the `main` branch
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  extends:
    - .build-and-push-gitlab

aggregate-http-manifests:
  stage: build
  needs:
    - build-http-app-amd64
    - build-http-app-arm64
  variables:
    DOCKER_IMAGE_NAME: $CI_PROJECT_NAME-http
  rules:
    # We run the pipeline only on merge requests or the `main` branch
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  extends:
    - .multiarch-manifest-gitlab

