# Build Docker image for test
build-test:
  stage: build
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  variables:
    DOCKER_BUILDKIT: 1
  before_script:
    - apk add --no-cache qemu bash git
  script:
    - docker buildx create --use
    - docker buildx inspect --bootstrap
    - |
      docker buildx build --load --target=dev --tag=$TEST_TAG \
      --cache-to=type=local,dest=/tmp/.buildx-cache \
      --cache-from=type=local,src=/tmp/.buildx-cache \
      .
  artifacts:
    paths:
      - /tmp/.buildx-cache
    expire_in: 1h


