@startuml
usecase base [
    =Base
    ----
    ""Contains system runtime ""
    ""libraries necessary to run""
    ""all the applications""
    ""(e.g. libmysql)""
]
usecase base_builder [
    =Base Builder
    ----
    ""Contains system libraries""
    ""necessary to build python""
    ""dependencies""
    ""(e.g. gcc, library headers)""
]
usecase dev [
    =Dev
    ----
    ""Fat image containing everything""
    ""necessary to run and test""
    ""all the applications""
]
usecase base_app [
    =Base app
    ----
    ""Copies shared application logic""
    ""independent from the used framework""
    ""(domains, storage, etc.)""
]

rectangle HTTP {
    usecase http_builder [
        =HTTP builder
        ----
        ""Builds HTTP dependencies""
    ]
    usecase http_app [
        =HTTP app
        ----
        ""Copies HTTP framework""
        ""shared logic""
        ""and dependencies""
        "" to run the application""
    ]
}
rectangle Celery {
    usecase celery_builder [
        =Celery builder
        ----
        ""Builds Celery dependencies""
    ]
    usecase celery_app [
        =Celery app
        ----
        ""Copies Celery framework""
        ""shared logic""
        ""and dependencies""
        "" to run the application""
    ]
}

base ==r=> base_builder
base ==l=> base_app

base_builder ===> http_builder
http_builder ===> http_app
base_app ===> http_app

base_builder ===> celery_builder
celery_builder ===> celery_app
base_app ===> celery_app

base_builder ==r=> dev
@enduml
