[tool.ruff]
# Extend the `pyproject.toml` file in the parent directory...
extend = "../../pyproject.toml"

[tool.ruff.lint.flake8-tidy-imports.banned-api]
"domains".msg = "Clean Architecture dependency rule break: import of `domains` is not allowed"
"dramatiq_worker".msg = "Clean Architecture dependency rule break: import of `dramatiq_worker` is not allowed"
"http_app".msg = "Clean Architecture dependency rule break: import of `http_app` is not allowed"
"gateways".msg = "Clean Architecture dependency rule break: import of `gateways` is not allowed"
"migrations".msg = "Clean Architecture dependency rule break: import of `migrations` is not allowed"
"socketio_app".msg = "Clean Architecture dependency rule break: import of `socketio_app` is not allowed"

# These ignore rules suggest these modules should not be inside `common`.
[tool.ruff.lint.per-file-ignores]
"storage/**/*.py" = ["TID251"]  # Storage is allowed to import domains module as it needs the models
"di_container.py" = ["TID251"]  # DI Container is allowed to import domains module
